pipeline{
  agent any{
    stages{
      stage('compile'){
        steps{
          maven compile
        }
      }
      stage('build'){
        steps{
          maven build
        }
      }
    }
  }
}
