pipeline{
  agent any
  tools {
    git 'git'
    maven 'maven'
  }
  {
    stages{
      stage('compile'){
        steps{
          maven compile
        }
      }
      stage('build'){
        steps{
          maven build
        }
      }
    }
  }
}
